# Gradle Properties
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true
org.gradle.java.home=C:\\Users\\yarov\\.jdks\\temurin-21.0.11

# Mod Properties
version = 0.0.1-alpha.1
maven_group = io.github.dragonrager
archives_base_name = blank_canvas

# Dependencies are managed at gradle/libs.versions.toml
